export default {
  FETCH_BATCHES_ATTEMPT: 'FETCH_BATCHES_ATTEMPT',
  FETCH_BATCHES: 'FETCH_BATCHES',
  FETCH_BATCHES_ERROR: 'FETCH_BATCHES_ERROR',

  FETCH_FROM_BATCH_ATTEMPT: 'FETCH_FROM_BATCH_ATTEMPT',
  FETCH_FROM_BATCH: 'FETCH_FROM_BATCH',
  FETCH_FROM_BATCH_ERROR: 'FETCH_FROM_BATCH_ERROR',

  FETCH_ATTRIBUTE_ATTEMPT: 'FETCH_ATTRIBUTE_ATTEMPT',
  FETCH_ATTRIBUTE: 'FETCH_ATTRIBUTE',
  FETCH_ATTRIBUTE_ERROR: 'FETCH_ATTRIBUTE_ERROR',

  FETCH_NEXT_ELEMENTS_ATTEMPT: 'FETCH_NEXT_ELEMENTS_ATTEMPT',
  FETCH_NEXT_ELEMENTS: 'FETCH_NEXT_ELEMENTS',
  FETCH_NEXT_ELEMENTS_ERROR: 'FETCH_NEXT_ELEMENTS_ERROR',

  SET_ACTIVE_BATCH: 'SET_ACTIVE_BATCH',
  UPDATE_THRESHOLD: 'UPDATE_THRESHOLD',
  UPDATE_LABEL: 'UPDATE_LABEL',
  /* CvJson */
  FETCH_RANKING: 'FETCH_RANKING'
}
