export default {
  FETCH_ELEMENTS_ATTEMPT: 'FETCH_ELEMENTS_ATTEMPT',
  FETCH_ELEMENTS: 'FETCH_ELEMENTS',
  FETCH_ELEMENTS_ERROR: 'FETCH_ELEMENTS_ERROR',
  SET_ACTIVE_BATCH: 'SET_ACTIVE_BATCH',
  /* CvJson */
  FETCH_NEXT_ELEMENTS_ATTEMPT: 'FETCH_NEXT_ELEMENTS_ATTEMPT',
  FETCH_NEXT_ELEMENTS: 'FETCH_NEXT_ELEMENTS',
  FETCH_NEXT_ELEMENTS_ERROR: 'FETCH_NEXT_ELEMENTS_ERROR',
  FETCH_RANKING: 'FETCH_RANKING'
}
